// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bwKu9pgF5MCbTv1pI3IV27GVp-ld9AM',
    appId: '1:961926660266:web:9c68162ccb121d272e50d3',
    messagingSenderId: '961926660266',
    projectId: 'flutter-68-1-016-sakda',
    authDomain: 'flutter-68-1-016-sakda.firebaseapp.com',
    storageBucket: 'flutter-68-1-016-sakda.firebasestorage.app',
    measurementId: 'G-KYJEJD3QF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASF284TgomWIH-GzCUT6SXlO_4qoX96j0',
    appId: '1:961926660266:android:c67f32f479e10c942e50d3',
    messagingSenderId: '961926660266',
    projectId: 'flutter-68-1-016-sakda',
    storageBucket: 'flutter-68-1-016-sakda.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkT8k72BXlZnSIrmFNFGmoXsZYCd4RP5E',
    appId: '1:961926660266:ios:bcc16b1b2c772d712e50d3',
    messagingSenderId: '961926660266',
    projectId: 'flutter-68-1-016-sakda',
    storageBucket: 'flutter-68-1-016-sakda.firebasestorage.app',
    iosBundleId: 'com.example.animeRuka',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkT8k72BXlZnSIrmFNFGmoXsZYCd4RP5E',
    appId: '1:961926660266:ios:bcc16b1b2c772d712e50d3',
    messagingSenderId: '961926660266',
    projectId: 'flutter-68-1-016-sakda',
    storageBucket: 'flutter-68-1-016-sakda.firebasestorage.app',
    iosBundleId: 'com.example.animeRuka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0bwKu9pgF5MCbTv1pI3IV27GVp-ld9AM',
    appId: '1:961926660266:web:e2a69b14a306ad452e50d3',
    messagingSenderId: '961926660266',
    projectId: 'flutter-68-1-016-sakda',
    authDomain: 'flutter-68-1-016-sakda.firebaseapp.com',
    storageBucket: 'flutter-68-1-016-sakda.firebasestorage.app',
    measurementId: 'G-RGFYMWTL7R',
  );
}
